name: Build

on: [push]

jobs:
  build_api:
    name: API Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      working-directory: api
      run: npm i
    - name: Build
      working-directory: api
      run: npm run build
  build_web:
    runs-on: ubuntu-latest
    name: Web Build
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      working-directory: adventskalender
      run: npm i
    - name: Build
      working-directory: adventskalender
      run: npm run build
  build_docker:
    if: github.ref == 'refs/heads/master'
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install frontend dependencies
      working-directory: adventskalender
      run: npm i
    - name: Install backend dependencies
      working-directory: api
      run: npm i
    - name: Build
      working-directory: docker
      run: sudo bash ./build.sh
    - name: Deploy to Docker Hub
      working-directory: docker
      run: sudo bash ./deploy.sh ${{ secrets.DOCKER_HUB_USERNAME }} ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}