name: Lint

on: [push]

jobs:
  lint_web_frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      working-directory: adventskalender
      run: npm i
    - name: Lint
      working-directory: adventskalender
      run: npm run lint
  lint_api:
    name: Lint API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      working-directory: api
      run: npm i
    - name: Lint
      working-directory: api
      run: npm run lint
